/*********************************************************************
	schef database schema postgres migration

		* Create Schema for schef in PostgreSQL

*********************************************************************/

-- Table: cell5m_area

-- DROP TABLE cell5m_area;
CREATE TABLE IF NOT EXISTS cell5m_area
(
  cell5m integer,
  pct_rur numeric,
  pct_urb numeric,
  pct_rur_100 numeric,
  pct_urb_100 numeric,
  area_total numeric,
  area_rur numeric,
  area_urb numeric,
  area_wbody numeric,
  area_land numeric,
  area_cr_lc bigint,
  area_irr bigint
);

-- Table: cell5m_bio

-- DROP TABLE cell5m_bio;
CREATE TABLE IF NOT EXISTS cell5m_bio
(
  cell5m integer,
  aez16_clas varchar,
  aez16_code integer,
  aez5_clas varchar,
  aez8_clas varchar,
  elevation numeric,
  lgp_avg numeric,
  lgp_cv numeric,
  lgp_text varchar,
  maj_name varchar,
  pre_avg numeric,
  pre_cv numeric
);

-- Table: cell5m_dhs

-- DROP TABLE cell5m_dhs;

CREATE TABLE IF NOT EXISTS cell5m_dhs
(
  cell5m integer,
  svycode varchar,
  svyl1nm varchar,
  m4_duration numeric,
  m5_duration numeric,
  mother_age numeric,
  mother_weight_kgs numeric,
  mother_height_cms numeric,
  bmi numeric,
  child_mortality numeric,
  infant_mortality numeric,
  vitamin_a numeric,
  iron numeric,
  stunted_low numeric,
  stunted_moderate numeric,
  stunted_severe numeric,
  wasted_low numeric,
  wasted_moderate numeric,
  wasted_severe numeric,
  underweight_low numeric,
  underweight_moderate numeric,
  underweight_severe numeric,
  bmi_normal numeric,
  bmi_normal_adj numeric,
  bmi_obese numeric,
  bmi_obese_adj numeric,
  bmi_overweight numeric,
  bmi_overweight_adj numeric,
  bmi_underweight numeric,
  bmi_underweight_adj numeric,
  diarrhea numeric,
  wealth numeric,
  m4_duration_rur numeric,
  m5_duration_rur numeric,
  mother_age_rur numeric,
  mother_weight_kgs_rur numeric,
  mother_height_cms_rur numeric,
  bmi_rur numeric,
  child_mortality_rur numeric,
  infant_mortality_rur numeric,
  vitamin_a_rur numeric,
  iron_rur numeric,
  stunted_low_rur numeric,
  stunted_moderate_rur numeric,
  stunted_severe_rur numeric,
  wasted_low_rur numeric,
  wasted_moderate_rur numeric,
  wasted_severe_rur numeric,
  underweight_low_rur numeric,
  underweight_moderate_rur numeric,
  underweight_severe_rur numeric,
  bmi_normal_rur numeric,
  bmi_normal_adj_rur numeric,
  bmi_obese_rur numeric,
  bmi_obese_adj_rur numeric,
  bmi_overweight_rur numeric,
  bmi_overweight_adj_rur numeric,
  bmi_underweight_rur numeric,
  bmi_underweight_adj_rur numeric,
  diarrhea_rur numeric,
  wealth_rur numeric,
  m4_duration_urb numeric,
  m5_duration_urb numeric,
  mother_age_urb numeric,
  mother_weight_kgs_urb numeric,
  mother_height_cms_urb numeric,
  bmi_urb numeric,
  child_mortality_urb numeric,
  infant_mortality_urb numeric,
  vitamin_a_urb numeric,
  iron_urb numeric,
  stunted_low_urb numeric,
  stunted_moderate_urb numeric,
  stunted_severe_urb numeric,
  wasted_low_urb numeric,
  wasted_moderate_urb numeric,
  wasted_severe_urb numeric,
  underweight_low_urb numeric,
  underweight_moderate_urb numeric,
  underweight_severe_urb numeric,
  bmi_normal_urb numeric,
  bmi_normal_adj_urb numeric,
  bmi_obese_urb numeric,
  bmi_obese_adj_urb numeric,
  bmi_overweight_urb numeric,
  bmi_overweight_adj_urb numeric,
  bmi_underweight_urb numeric,
  bmi_underweight_adj_urb numeric,
  diarrhea_urb numeric,
  wealth_urb numeric,
  weight_rur numeric,
  weight_urb numeric,
  weight numeric
);

-- Table: cell5m_fcc

-- DROP TABLE cell5m_fcc;

CREATE TABLE IF NOT EXISTS cell5m_fcc
(
  cell5m integer NOT NULL,
  salum bigint,
  scalc bigint,
  sleach bigint,
  swater bigint,
  spfh bigint,
  slnc bigint,
  ssod bigint,
  ssal bigint,
  scrac bigint,
  svolc bigint,
  ssand bigint,
  sloam bigint,
  sclay bigint
);

-- Table: cell5m_fs

-- DROP TABLE cell5m_fs;

CREATE TABLE IF NOT EXISTS cell5m_fs
(
  objectid_1 integer,
  fid_1 integer,
  alloc_key character varying(8),
  cell5m integer,
  fips0 character varying(2),
  iso3_cntr character varying(254),
  gaul_cntr real,
  gaul_name character varying(254),
  fs_2012 integer,
  fs_2012_tx character varying(40),
  lev_2 integer,
  sub_syst character varying(60)
);

-- Table: cell5m_gmia_v5

-- DROP TABLE cell5m_gmia_v5;

CREATE TABLE IF NOT EXISTS cell5m_gmia_v5
(
  objectid_1 integer,
  fid_1 integer,
  alloc_key character varying(8),
  cell5m integer,
  fips0 character varying(2),
  iso3_cntr character varying(254),
  gaul_cntr real,
  gaul_name character varying(254),
  gmia_v5 real
);

-- Table: cell5m_grid

-- DROP TABLE cell5m_grid;

CREATE TABLE IF NOT EXISTS cell5m_grid
(
  cell5m integer,
  iso3 character varying,
  adm0_code integer,
  adm0_name character varying,
  adm1_code integer,
  adm1_name character varying,
  adm2_code integer,
  adm2_name character varying,
  adm1_code_alt integer,
  adm1_name_alt character varying,
  adm2_code_alt integer,
  adm2_name_alt character varying,
  x numeric,
  y numeric
);

-- Table: cell5m_lstock

-- DROP TABLE cell5m_lstock;

CREATE TABLE IF NOT EXISTS cell5m_lstock
(
  cell5m integer NOT NULL,
  ad05_catt numeric,
  ad05_chic numeric,
  ad05_goat numeric,
  ad05_lu numeric,
  ad05_pig numeric,
  ad05_shee numeric,
  ad05_tlu numeric,
  an05_catt numeric,
  an05_chic numeric,
  an05_goat numeric,
  an05_pig numeric,
  an05_shee numeric,
  an05_lu numeric,
  an05_tlu numeric
);

-- Table: cell5m_pest

-- DROP TABLE cell5m_pest;

CREATE TABLE IF NOT EXISTS cell5m_pest
(
  cell5m numeric,
  rf_gi numeric,
  rf_ei numeric,
  rf_gi_clas character varying,
  rf_ei_clas character varying,
  ir_gi numeric,
  ir_ei numeric,
  ir_gi_clas character varying,
  ir_ei_clas character varying
);

CREATE TABLE IF NOT EXISTS cell5m_pop_00(
	CELL5M integer NOT NULL,
	RPOV_NR075 bigint,
	RPOV_NR125 bigint,
	RPOV_NR200 bigint,
	TPOV_NR075 bigint,
	TPOV_NR125 bigint,
	TPOV_NR200 bigint,
	TPOV_PT075 numeric,
	PD00_RUR numeric,
	PN00_RUR bigint,
	PN00_TOT bigint,
	PN00_URB bigint,
	SVY_POV varchar,
	SVY_POP varchar
);

CREATE TABLE IF NOT EXISTS cell5m_pop_05(
	CELL5M numeric,
	PN05_URB numeric,
	PN05_RUR numeric,
	PN05_TOT numeric,
	PD05_RUR numeric,
	PD05_URB numeric,
	PD05_TOT numeric
);


CREATE TABLE IF NOT EXISTS cell5m_pov_05(
	CELL5M integer,
	ISO3 varchar,
	year integer,
	svyCode varchar,
	svyL1Cd integer,
	svyL1Nm varchar,
	prttyNm varchar,
	UPOV_PT125 numeric,
	RPOV_PT125 numeric,
	UPOV_PT200 numeric,
	RPOV_PT200 numeric,
	UPOV_GAP125 numeric,
	RPOV_GAP125 numeric,
	UPOV_GAP200 numeric,
	RPOV_GAP200 numeric,
	UPOV_SEV125 numeric,
	RPOV_SEV125 numeric,
	UPOV_SEV200 numeric,
	RPOV_SEV200 numeric,
	UPOV_SD125 numeric,
	RPOV_SD125 numeric,
	UPOV_SD200 numeric,
	RPOV_SD200 numeric,
	UPOV_PCEXP numeric,
	RPOV_PCEXP numeric,
	UPOV_GINI numeric,
	RPOV_GINI numeric,
	TPOV_PT125 numeric,
	TPOV_PT200 numeric,
	TPOV_GAP125 numeric,
	TPOV_GAP200 numeric,
	TPOV_SEV125 numeric,
	TPOV_SEV200 numeric,
	TPOV_SD125 numeric,
	TPOV_SD200 numeric,
	TPOV_PCEXP numeric,
	TPOV_GINI numeric,
	UPOV_PD125 numeric,
	RPOV_PD125 numeric,
	TPOV_PD125 numeric,
	UPOV_PD200 numeric,
	RPOV_PD200 numeric,
	TPOV_PD200 numeric
);
-- Table: cell5m_spam2005v1_group_harvestarea

-- DROP TABLE cell5m_spam2005v1_group_harvestarea;

CREATE TABLE IF NOT EXISTS cell5m_spam2005v1_group_harvestarea
(
  iso3 character varying(3),
  prod_level character varying(7),
  alloc_key character varying(8),
  cell5m integer,
  rec_type character varying(1),
  unit character varying(6),
  cere_h numeric,
  mill_h numeric,
  puls_h numeric,
  coff_h numeric,
  bapl_h numeric,
  frui_h numeric,
  cere_r_h numeric,
  cere_i_h numeric,
  mill_r_h numeric,
  mill_i_h numeric,
  puls_r_h numeric,
  puls_i_h numeric,
  coff_r_h numeric,
  coff_i_h numeric,
  bapl_r_h numeric,
  bapl_i_h numeric,
  frui_r_h numeric,
  frui_i_h numeric,
  crea_date character varying(20),
  year_data character varying(15),
  source character varying(30),
  scale_year character varying(15),
  name_cntr character varying(30),
  name_adm1 character varying(30)
);

-- Table: cell5m_spam2005v1_group_production

-- DROP TABLE cell5m_spam2005v1_group_production;

CREATE TABLE IF NOT EXISTS cell5m_spam2005v1_group_production
(
  iso3 character varying(3),
  prod_level character varying(7),
  alloc_key character varying(8),
  cell5m integer,
  rec_type character varying(1),
  unit character varying(6),
  cere_p numeric,
  mill_p numeric,
  puls_p numeric,
  coff_p numeric,
  bapl_p numeric,
  frui_p numeric,
  cere_r_p numeric,
  cere_i_p numeric,
  mill_i_p numeric,
  mill_r_p numeric,
  puls_r_p numeric,
  puls_i_p numeric,
  coff_r_p numeric,
  coff_i_p numeric,
  bapl_r_p numeric,
  bapl_i_p numeric,
  frui_r_p numeric,
  frui_i_p numeric,
  crea_date character varying(20),
  year_data character varying(15),
  source character varying(30),
  scale_year character varying(15),
  name_cntr character varying(30),
  name_adm1 character varying(30)
);

-- Table: cell5m_spam2005v1_group_valprod

-- DROP TABLE cell5m_spam2005v1_group_valprod;

CREATE TABLE IF NOT EXISTS cell5m_spam2005v1_group_valprod
(
  iso3 character varying(3),
  prod_level character varying(7),
  alloc_key character varying(8),
  cell5m integer,
  rec_type character varying(1),
  unit character varying(6),
  cere_v numeric,
  mill_v numeric,
  puls_v numeric,
  coff_v numeric,
  bapl_v numeric,
  frui_v numeric,
  crea_date character varying(20),
  year_data character varying(15),
  source character varying(30),
  scale_year character varying(15),
  name_cntr character varying(30),
  name_adm1 character varying(30)
);

-- Table: cell5m_spam2005v1_group_yield

-- DROP TABLE cell5m_spam2005v1_group_yield;

CREATE TABLE IF NOT EXISTS cell5m_spam2005v1_group_yield
(
  iso3 character varying(3),
  prod_level character varying(7),
  alloc_key character varying(8),
  cell5m integer,
  rec_type character varying(1),
  unit character varying(6),
  cere_y numeric,
  mill_y numeric,
  puls_y numeric,
  coff_y numeric,
  bapl_y numeric,
  frui_y numeric,
  cere_r_y numeric,
  cere_i_y numeric,
  mill_r_y numeric,
  mill_i_y numeric,
  puls_r_y numeric,
  puls_i_y numeric,
  coff_r_y numeric,
  coff_i_y numeric,
  bapl_r_y numeric,
  bapl_i_y numeric,
  frui_r_y numeric,
  frui_i_y numeric,
  crea_date character varying(20),
  year_data character varying(15),
  source character varying(30),
  scale_year character varying(15),
  name_cntr character varying(30),
  name_adm1 character varying(30)
);

-- Table: cell5m_spam2005v1_harvestarea

-- DROP TABLE cell5m_spam2005v1_harvestarea;

CREATE TABLE IF NOT EXISTS cell5m_spam2005v1_harvestarea
(
  iso3 character varying(3),
  prod_level character varying(7),
  alloc_key character varying(8),
  cell5m integer,
  rec_type character varying(1),
  unit character varying(6),
  whea_h numeric,
  rice_h numeric,
  maiz_h numeric,
  barl_h numeric,
  pmil_h numeric,
  smil_h numeric,
  sorg_h numeric,
  ocer_h numeric,
  pota_h numeric,
  swpo_h numeric,
  yams_h numeric,
  cass_h numeric,
  orts_h numeric,
  bean_h numeric,
  chic_h numeric,
  cowp_h numeric,
  pige_h numeric,
  lent_h numeric,
  opul_h numeric,
  soyb_h numeric,
  grou_h numeric,
  cnut_h numeric,
  oilp_h numeric,
  sunf_h numeric,
  rape_h numeric,
  sesa_h numeric,
  ooil_h numeric,
  sugc_h numeric,
  sugb_h numeric,
  cott_h numeric,
  ofib_h numeric,
  acof_h numeric,
  rcof_h numeric,
  coco_h numeric,
  teas_h numeric,
  toba_h numeric,
  bana_h numeric,
  plnt_h numeric,
  trof_h numeric,
  temf_h numeric,
  vege_h numeric,
  rest_h numeric,
  whea_r_h numeric,
  whea_i_h numeric,
  rice_r_h numeric,
  rice_i_h numeric,
  maiz_r_h numeric,
  maiz_i_h numeric,
  barl_r_h numeric,
  barl_i_h numeric,
  pmil_r_h numeric,
  pmil_i_h numeric,
  smil_r_h numeric,
  smil_i_h numeric,
  sorg_r_h numeric,
  sorg_i_h numeric,
  ocer_r_h numeric,
  ocer_i_h numeric,
  pota_r_h numeric,
  pota_i_h numeric,
  swpo_r_h numeric,
  swpo_i_h numeric,
  yams_r_h numeric,
  yams_i_h numeric,
  cass_r_h numeric,
  cass_i_h numeric,
  orts_r_h numeric,
  orts_i_h numeric,
  bean_r_h numeric,
  bean_i_h numeric,
  chic_r_h numeric,
  chic_i_h numeric,
  cowp_r_h numeric,
  cowp_i_h numeric,
  pige_r_h numeric,
  pige_i_h numeric,
  lent_r_h numeric,
  lent_i_h numeric,
  opul_r_h numeric,
  opul_i_h numeric,
  soyb_r_h numeric,
  soyb_i_h numeric,
  grou_r_h numeric,
  grou_i_h numeric,
  cnut_r_h numeric,
  cnut_i_h numeric,
  oilp_r_h numeric,
  oilp_i_h numeric,
  sunf_r_h numeric,
  sunf_i_h numeric,
  rape_r_h numeric,
  rape_i_h numeric,
  sesa_r_h numeric,
  sesa_i_h numeric,
  ooil_r_h numeric,
  ooil_i_h numeric,
  sugc_r_h numeric,
  sugc_i_h numeric,
  sugb_r_h numeric,
  sugb_i_h numeric,
  cott_r_h numeric,
  cott_i_h numeric,
  ofib_r_h numeric,
  ofib_i_h numeric,
  acof_r_h numeric,
  acof_i_h numeric,
  rcof_r_h numeric,
  rcof_i_h numeric,
  coco_r_h numeric,
  coco_i_h numeric,
  teas_r_h numeric,
  teas_i_h numeric,
  toba_r_h numeric,
  toba_i_h numeric,
  bana_r_h numeric,
  bana_i_h numeric,
  plnt_r_h numeric,
  plnt_i_h numeric,
  trof_r_h numeric,
  trof_i_h numeric,
  temf_r_h numeric,
  temf_i_h numeric,
  vege_r_h numeric,
  vege_i_h numeric,
  rest_r_h numeric,
  rest_i_h numeric,
  crea_date character varying(20),
  year_data character varying(15),
  source character varying(30),
  scale_year character varying(15),
  name_cntr character varying(30),
  name_adm1 character varying(30)
);

-- Table: cell5m_spam2005v1_production

-- DROP TABLE cell5m_spam2005v1_production;

CREATE TABLE IF NOT EXISTS cell5m_spam2005v1_production
(
  iso3 character varying(3),
  prod_level character varying(7),
  alloc_key character varying(8),
  cell5m integer,
  rec_type character varying(1),
  unit character varying(6),
  whea_p numeric,
  rice_p numeric,
  maiz_p numeric,
  barl_p numeric,
  pmil_p numeric,
  smil_p numeric,
  sorg_p numeric,
  ocer_p numeric,
  pota_p numeric,
  swpo_p numeric,
  yams_p numeric,
  cass_p numeric,
  orts_p numeric,
  bean_p numeric,
  chic_p numeric,
  cowp_p numeric,
  pige_p numeric,
  lent_p numeric,
  opul_p numeric,
  soyb_p numeric,
  grou_p numeric,
  cnut_p numeric,
  oilp_p numeric,
  sunf_p numeric,
  rape_p numeric,
  sesa_p numeric,
  ooil_p numeric,
  sugc_p numeric,
  sugb_p numeric,
  cott_p numeric,
  ofib_p numeric,
  acof_p numeric,
  rcof_p numeric,
  coco_p numeric,
  teas_p numeric,
  toba_p numeric,
  bana_p numeric,
  plnt_p numeric,
  trof_p numeric,
  temf_p numeric,
  vege_p numeric,
  rest_p numeric,
  whea_r_p numeric,
  whea_i_p numeric,
  rice_r_p numeric,
  rice_i_p numeric,
  maiz_r_p numeric,
  maiz_i_p numeric,
  barl_r_p numeric,
  barl_i_p numeric,
  pmil_r_p numeric,
  pmil_i_p numeric,
  smil_r_p numeric,
  smil_i_p numeric,
  sorg_r_p numeric,
  sorg_i_p numeric,
  ocer_r_p numeric,
  ocer_i_p numeric,
  pota_r_p numeric,
  pota_i_p numeric,
  swpo_r_p numeric,
  swpo_i_p numeric,
  yams_r_p numeric,
  yams_i_p numeric,
  cass_r_p numeric,
  cass_i_p numeric,
  orts_r_p numeric,
  orts_i_p numeric,
  bean_r_p numeric,
  bean_i_p numeric,
  chic_r_p numeric,
  chic_i_p numeric,
  cowp_r_p numeric,
  cowp_i_p numeric,
  pige_r_p numeric,
  pige_i_p numeric,
  lent_r_p numeric,
  lent_i_p numeric,
  opul_r_p numeric,
  opul_i_p numeric,
  soyb_r_p numeric,
  soyb_i_p numeric,
  grou_r_p numeric,
  grou_i_p numeric,
  cnut_r_p numeric,
  cnut_i_p numeric,
  oilp_r_p numeric,
  oilp_i_p numeric,
  sunf_r_p numeric,
  sunf_i_p numeric,
  rape_r_p numeric,
  rape_i_p numeric,
  sesa_r_p numeric,
  sesa_i_p numeric,
  ooil_r_p numeric,
  ooil_i_p numeric,
  sugc_r_p numeric,
  sugc_i_p numeric,
  sugb_r_p numeric,
  sugb_i_p numeric,
  cott_r_p numeric,
  cott_i_p numeric,
  ofib_r_p numeric,
  ofib_i_p numeric,
  acof_r_p numeric,
  acof_i_p numeric,
  rcof_r_p numeric,
  rcof_i_p numeric,
  coco_r_p numeric,
  coco_i_p numeric,
  teas_r_p numeric,
  teas_i_p numeric,
  toba_r_p numeric,
  toba_i_p numeric,
  bana_r_p numeric,
  bana_i_p numeric,
  plnt_r_p numeric,
  plnt_i_p numeric,
  trof_r_p numeric,
  trof_i_p numeric,
  temf_r_p numeric,
  temf_i_p numeric,
  vege_r_p numeric,
  vege_i_p numeric,
  rest_r_p numeric,
  rest_i_p numeric,
  crea_date character varying(20),
  year_data character varying(15),
  source character varying(30),
  scale_year character varying(15),
  name_cntr character varying(30),
  name_adm1 character varying(30)
);

-- Table: cell5m_spam2005v1_valprod

-- DROP TABLE cell5m_spam2005v1_valprod;

CREATE TABLE IF NOT EXISTS cell5m_spam2005v1_valprod
(
  iso3 character varying(3),
  prod_level character varying(7),
  alloc_key character varying(8),
  cell5m integer,
  rec_type character varying(1),
  unit character varying(6),
  whea_v numeric,
  rice_v numeric,
  maiz_v numeric,
  barl_v numeric,
  pmil_v numeric,
  smil_v numeric,
  sorg_v numeric,
  ocer_v numeric,
  pota_v numeric,
  swpo_v numeric,
  yams_v numeric,
  cass_v numeric,
  orts_v numeric,
  bean_v numeric,
  chic_v numeric,
  cowp_v numeric,
  pige_v numeric,
  lent_v numeric,
  opul_v numeric,
  soyb_v numeric,
  grou_v numeric,
  cnut_v numeric,
  oilp_v numeric,
  sunf_v numeric,
  rape_v numeric,
  sesa_v numeric,
  ooil_v numeric,
  sugc_v numeric,
  sugb_v numeric,
  cott_v numeric,
  ofib_v numeric,
  acof_v numeric,
  rcof_v numeric,
  coco_v numeric,
  teas_v numeric,
  toba_v numeric,
  bana_v numeric,
  plnt_v numeric,
  trof_v numeric,
  temf_v numeric,
  vege_v numeric,
  rest_v numeric,
  crea_date character varying(20),
  year_data character varying(15),
  source character varying(30),
  scale_year character varying(15),
  name_cntr character varying(30),
  name_adm1 character varying(30)
);

-- Table: cell5m_spam2005v1_valprodagg

-- DROP TABLE cell5m_spam2005v1_valprodagg;

CREATE TABLE IF NOT EXISTS cell5m_spam2005v1_valprodagg
(
  iso3 character varying(3),
  prod_level character varying(7),
  alloc_key character varying(8),
  cell5m integer,
  rec_type character varying(1),
  unit character varying(6),
  vp_crop numeric,
  vp_food numeric,
  vp_nonf numeric,
  area_crop numeric,
  area_food numeric,
  area_nonf numeric,
  vp_crop_ar numeric,
  vp_food_ar numeric,
  vp_nonf_ar numeric,
  crea_date character varying(20),
  year_data character varying(15),
  name_cntr character varying(30)
);

-- Table: cell5m_spam2005v1_yield

-- DROP TABLE cell5m_spam2005v1_yield;

CREATE TABLE cell5m_spam2005v1_yield
(
  iso3 character varying(3),
  prod_level character varying(7),
  alloc_key character varying(8),
  cell5m integer,
  rec_type character varying(1),
  unit character varying(6),
  whea_y numeric,
  rice_y numeric,
  maiz_y numeric,
  barl_y numeric,
  pmil_y numeric,
  smil_y numeric,
  sorg_y numeric,
  ocer_y numeric,
  pota_y numeric,
  swpo_y numeric,
  yams_y numeric,
  cass_y numeric,
  orts_y numeric,
  bean_y numeric,
  chic_y numeric,
  cowp_y numeric,
  pige_y numeric,
  lent_y numeric,
  opul_y numeric,
  soyb_y numeric,
  grou_y numeric,
  cnut_y numeric,
  oilp_y numeric,
  sunf_y numeric,
  rape_y numeric,
  sesa_y numeric,
  ooil_y numeric,
  sugc_y numeric,
  sugb_y numeric,
  cott_y numeric,
  ofib_y numeric,
  acof_y numeric,
  rcof_y numeric,
  coco_y numeric,
  teas_y numeric,
  toba_y numeric,
  bana_y numeric,
  plnt_y numeric,
  trof_y numeric,
  temf_y numeric,
  vege_y numeric,
  rest_y numeric,
  whea_r_y numeric,
  whea_i_y numeric,
  rice_r_y numeric,
  rice_i_y numeric,
  maiz_r_y numeric,
  maiz_i_y numeric,
  barl_r_y numeric,
  barl_i_y numeric,
  pmil_r_y numeric,
  pmil_i_y numeric,
  smil_r_y numeric,
  smil_i_y numeric,
  sorg_r_y numeric,
  sorg_i_y numeric,
  ocer_r_y numeric,
  ocer_i_y numeric,
  pota_r_y numeric,
  pota_i_y numeric,
  swpo_r_y numeric,
  swpo_i_y numeric,
  yams_r_y numeric,
  yams_i_y numeric,
  cass_r_y numeric,
  cass_i_y numeric,
  orts_r_y numeric,
  orts_i_y numeric,
  bean_r_y numeric,
  bean_i_y numeric,
  chic_r_y numeric,
  chic_i_y numeric,
  cowp_r_y numeric,
  cowp_i_y numeric,
  pige_r_y numeric,
  pige_i_y numeric,
  lent_r_y numeric,
  lent_i_y numeric,
  opul_r_y numeric,
  opul_i_y numeric,
  soyb_r_y numeric,
  soyb_i_y numeric,
  grou_r_y numeric,
  grou_i_y numeric,
  cnut_r_y numeric,
  cnut_i_y numeric,
  oilp_r_y numeric,
  oilp_i_y numeric,
  sunf_r_y numeric,
  sunf_i_y numeric,
  rape_r_y numeric,
  rape_i_y numeric,
  sesa_r_y numeric,
  sesa_i_y numeric,
  ooil_r_y numeric,
  ooil_i_y numeric,
  sugc_r_y numeric,
  sugc_i_y numeric,
  sugb_r_y numeric,
  sugb_i_y numeric,
  cott_r_y numeric,
  cott_i_y numeric,
  ofib_r_y numeric,
  ofib_i_y numeric,
  acof_r_y numeric,
  acof_i_y numeric,
  rcof_r_y numeric,
  rcof_i_y numeric,
  coco_r_y numeric,
  coco_i_y numeric,
  teas_r_y numeric,
  teas_i_i numeric,
  toba_r_y numeric,
  toba_i_y numeric,
  bana_r_y numeric,
  bana_i_y numeric,
  plnt_r_y numeric,
  plnt_i_y numeric,
  trof_r_y numeric,
  trof_i_y numeric,
  temf_r_y numeric,
  temf_i_y numeric,
  vege_r_y numeric,
  vege_i_y numeric,
  rest_r_y numeric,
  rest_i_y numeric,
  crea_date character varying(20),
  year_data character varying(15),
  source character varying(30),
  scale_year character varying(15),
  name_cntr character varying(30),
  name_adm1 character varying(30)
);

-- Table: cell5m_tt

-- DROP TABLE cell5m_tt;

CREATE TABLE IF NOT EXISTS cell5m_tt
(
  cell5m integer NOT NULL,
  msh_20k_id bigint,
  msh_50k_id bigint,
  msh_100k_id bigint,
  msh_250k_id bigint,
  msh_500k_id bigint,
  msh_50k_tx character varying(60),
  psh_id bigint,
  psh_iso3 character varying(3),
  psh_tx character varying(60),
  tt_20k numeric,
  tt_50k numeric,
  tt_100k numeric,
  tt_250k numeric,
  tt_500k numeric,
  tt_port numeric
);


-- Table: cell5m_wdpa2009

-- DROP TABLE cell5m_wdpa2009;

CREATE TABLE IF NOT EXISTS cell5m_wdpa2009
(
  cell5m integer NOT NULL,
  wdpa_pct integer,
  CONSTRAINT cell5m_wdpa2009_pkey PRIMARY KEY (cell5m)
);

-- Index: cell5m_wdpa2009_index

-- DROP INDEX cell5m_wdpa2009_index;

CREATE INDEX cell5m_wdpa2009_index
  ON cell5m_wdpa2009
  USING btree
  (cell5m);
