//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarvestChoiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class classification
    {
        public classification()
        {
            this.continuous_classification = new HashSet<continuous_classification>();
            this.discrete_classification = new HashSet<discrete_classification>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    
        public virtual ICollection<continuous_classification> continuous_classification { get; set; }
        public virtual ICollection<discrete_classification> discrete_classification { get; set; }
    }
}
