//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarvestChoiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection
    {
        public collection()
        {
            this.collection_group = new HashSet<collection_group>();
            this.country_collection = new HashSet<country_collection>();
        }
    
        public string name { get; set; }
        public string label { get; set; }
        public string code { get; set; }
    
        public virtual ICollection<collection_group> collection_group { get; set; }
        public virtual ICollection<country_collection> country_collection { get; set; }
    }
}
