//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarvestChoiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class domain_variable
    {
        public domain_variable()
        {
            this.continuous_classification = new HashSet<continuous_classification>();
            this.discrete_classification = new HashSet<discrete_classification>();
            this.schema_domain = new HashSet<schema_domain>();
        }
    
        public int id { get; set; }
        public string column_name { get; set; }
        public string micro_label { get; set; }
        public string short_label { get; set; }
        public string full_label { get; set; }
        public string long_description { get; set; }
        public string category_1 { get; set; }
        public string category_2 { get; set; }
        public string category_3 { get; set; }
        public string item { get; set; }
        public string unit { get; set; }
        public Nullable<int> decimal_places { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> end_year { get; set; }
        public string extent { get; set; }
        public string classification_type { get; set; }
        public string agg_type { get; set; }
        public string agg_formula { get; set; }
        public string table_name { get; set; }
        public string column_label { get; set; }
        public string table_unique_id { get; set; }
        public string source { get; set; }
        public string micro_source { get; set; }
        public string data_worker { get; set; }
        public string createdby { get; set; }
        public string createddate { get; set; }
        public Nullable<bool> published { get; set; }
        public Nullable<bool> validated { get; set; }
        public string last_processed { get; set; }
        public string processing_comment { get; set; }
        public string version { get; set; }
        public string caveat { get; set; }
    
        public virtual ICollection<continuous_classification> continuous_classification { get; set; }
        public virtual ICollection<discrete_classification> discrete_classification { get; set; }
        public virtual ICollection<schema_domain> schema_domain { get; set; }
    }
}
