//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarvestChoiceApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HC_WEB_DB_Connection : DbContext
    {
        public HC_WEB_DB_Connection()
            : base("name=HC_WEB_DB_Connection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CELL_VALUES> CELL_VALUES { get; set; }
        public DbSet<classification> classifications { get; set; }
        public DbSet<collection> collections { get; set; }
        public DbSet<collection_group> collection_group { get; set; }
        public DbSet<continuous_classification> continuous_classification { get; set; }
        public DbSet<country> countries { get; set; }
        public DbSet<country_collection> country_collection { get; set; }
        public DbSet<discrete_classification> discrete_classification { get; set; }
        public DbSet<domain_variable> domain_variable { get; set; }
        public DbSet<indicator_metadata> indicator_metadata { get; set; }
        public DbSet<schema> schemata { get; set; }
        public DbSet<schema_domain> schema_domain { get; set; }
        public DbSet<vCountryList> vCountryLists { get; set; }
    
        public virtual int udf_ExecuteSQLStatemnt(string sQLStatement)
        {
            var sQLStatementParameter = sQLStatement != null ?
                new ObjectParameter("SQLStatement", sQLStatement) :
                new ObjectParameter("SQLStatement", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("udf_ExecuteSQLStatemnt", sQLStatementParameter);
        }
    }
}
