//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarvestChoiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.country_collection = new HashSet<country_collection>();
            this.domain_country_results = new HashSet<domain_country_results>();
        }
    
        public string name { get; set; }
        public string label { get; set; }
        public string id { get; set; }
        public System.Data.Entity.Spatial.DbGeometry shape { get; set; }
    
        public virtual ICollection<country_collection> country_collection { get; set; }
        public virtual ICollection<domain_country_results> domain_country_results { get; set; }
    }
}
