//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarvestChoiceApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HC_Entities : DbContext
    {
        public HC_Entities()
            : base("name=HC_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CELL_VALUES> CELL_VALUES { get; set; }
        public DbSet<CELL_VALUES_old> CELL_VALUES_old { get; set; }
        public DbSet<classification> classifications { get; set; }
        public DbSet<collection> collections { get; set; }
        public DbSet<collection_group> collection_group { get; set; }
        public DbSet<continuous_classification> continuous_classification { get; set; }
        public DbSet<country> countries { get; set; }
        public DbSet<country_collection> country_collection { get; set; }
        public DbSet<discrete_classification> discrete_classification { get; set; }
        public DbSet<domain_country_results> domain_country_results { get; set; }
        public DbSet<domain_variable> domain_variable { get; set; }
        public DbSet<GAUL_2008_1> GAUL_2008_1 { get; set; }
        public DbSet<GAUL_2012_1> GAUL_2012_1 { get; set; }
        public DbSet<indicator_metadata> indicator_metadata { get; set; }
        public DbSet<ISO3> ISO3 { get; set; }
        public DbSet<schema> schemata { get; set; }
        public DbSet<schema_domain> schema_domain { get; set; }
        public DbSet<vCountryList> vCountryLists { get; set; }
        public DbSet<vGAUL_2008> vGAUL_2008 { get; set; }
    }
}
