//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarvestChoiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class indicator_metadata
    {
        public int ID { get; set; }
        public Nullable<int> vi_id { get; set; }
        public string varCode { get; set; }
        public string varLabel { get; set; }
        public Nullable<bool> published { get; set; }
        public string tbName { get; set; }
        public string version { get; set; }
        public string tbKey { get; set; }
        public string varTitle { get; set; }
        public string varDesc { get; set; }
        public string unit { get; set; }
        public Nullable<int> dec { get; set; }
        public string year { get; set; }
        public Nullable<int> yearEnd { get; set; }
        public string cat1 { get; set; }
        public string cat2 { get; set; }
        public string cat3 { get; set; }
        public string extent { get; set; }
        public string type { get; set; }
        public string aggType { get; set; }
        public string aggFun { get; set; }
        public string owner { get; set; }
        public string caveat { get; set; }
        public string sources { get; set; }
        public string sourceMini { get; set; }
        public Nullable<bool> genRaster { get; set; }
        public Nullable<bool> isDomain { get; set; }
        public Nullable<bool> isProduct { get; set; }
        public string mxdName { get; set; }
        public string classColors { get; set; }
        public string classBreaks { get; set; }
        public string classLabels { get; set; }
        public string dataType { get; set; }
    }
}
