//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarvestChoiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schema
    {
        public schema()
        {
            this.domain_country_results = new HashSet<domain_country_results>();
            this.schema_domain = new HashSet<schema_domain>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public string name { get; set; }
        public string preview_url { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string long_description { get; set; }
        public bool published { get; set; }
        public Nullable<bool> for_mappr { get; set; }
        public string restrictions { get; set; }
        public string json_geometry { get; set; }
    
        public virtual ICollection<domain_country_results> domain_country_results { get; set; }
        public virtual ICollection<schema_domain> schema_domain { get; set; }
    }
}
