//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarvestChoiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGAUL_2008
    {
        public int CELL5M { get; set; }
        public string GAUL_2008_1 { get; set; }
        public string GAUL_2008_2 { get; set; }
        public string ISO3 { get; set; }
    }
}
