//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarvestChoiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schema_domain
    {
        public int id { get; set; }
        public int schemaid { get; set; }
        public int domainid { get; set; }
    
        public virtual domain_variable domain_variable { get; set; }
        public virtual schema schema { get; set; }
    }
}
